# Site settings
title: What's The R-Squared?
email: mark.cyril.fruin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The primary purpose of this site is hockey analytics.  I reserve the
  right to cover any other area of interest, but posts will always 
  be data driven.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: frutoper
github_username:  frutoper

# Build settings
markdown: kramdown
